### ISSUE TITLE
Auto Formatter

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#792]
```yml
name: Formatter
on: push

jobs:
  fmtr:
    name: Fmt Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up
        uses: actions/setup-deno@master

      - name: Fmt
        run: deno fmt

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Your Name
          author_email: mail@example.com
          message: 'Your commit message'
          add: '*.js'
```
